spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres # PostgreSQL
    username: postgres # PostgreSQL
    password: admin # PostgreSQL
  jpa:
    hibernate:
      ddl-auto: create # drop n create table again, good for testing, comment this in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
